# datasource
spring:
  datasource:
    url: jdbc:mysql:///atm?useUnicode=true&characterEncoding=UTF-8   # /// 表示省略username IP 端口，都是默认
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
# server
#server:
#  port: 8081
